phase: train
dataset:
  scale: 1
  img_size: [480, 640]
  img_trans: center_crop  # chocies ['center_crop',' random_crop', 'resize', 'none']
  data_path: data/markerless
  kpt_path: data/marker_shift
  val_split: 0.2
  seed: 0
